"""update time_slot

Revision ID: 0170b535a75c
Revises: 219825ad5e04
Create Date: 2025-04-09 20:35:01.890651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0170b535a75c'
down_revision: Union[str, None] = '219825ad5e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('time_slot', sa.Column('version', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_slot', 'version')
    # ### end Alembic commands ###
