"""update reservation table

Revision ID: 0653062caebc
Revises: ff5133c6e75b
Create Date: 2025-04-08 23:21:21.752767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0653062caebc'
down_revision: Union[str, None] = 'ff5133c6e75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
