"""update reservation table

Revision ID: ff5133c6e75b
Revises: 57924aaa83ef
Create Date: 2025-04-08 22:40:30.009122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5133c6e75b'
down_revision: Union[str, None] = '57924aaa83ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'user_id')
    # ### end Alembic commands ###
